### ISSUE TITLE
Broken on 8.1

### ISSUE THREAD

**Issue by aleien** [wasabeef/Takt#11]
Hello!
Is library currently not supported? It looks like it doesn't work all good on 8.1 (didn't check other os versions). Also "how to use" is misleading.
1) You have to use '.showOverlaySetting(true)', otherwise it won't prompt you to enable setting (and without it it doesn't show
2) You have to add android.permission.SYSTEM_ALERT_WINDOW to your manifest, otherwise you won't be able to enable setting
3) Misleading guide: onTerminate won't be called ever, so Takt won't be finished until system kills your process, so you need to move Takt.finish() to some other place.

Also it may be only my problem, but it somehow duplicates one over other, even when launched only once, so it's essentially impossible to see current fps :(

**Comment by DEcSENT** [comment]
Working on android 4.4, but yes, broken on android 8.
